name: Release Build

permissions: write-all

on:
  push:
    tags:
      - "v*"           # Kích hoạt khi push tag bắt đầu với "v"
  workflow_dispatch:    # Cho phép kích hoạt thủ công

jobs:
  cross:
    name: Cross-Platform Build
    strategy:
      matrix:
        include:
          # Android ARM64-v8a
          - name: android-arm64-v8a
            goos: android
            goarch: arm64
            android_abi: arm64-v8a  # ABI Android chính xác

          # Linux AMD64
          - name: linux-amd64
            goos: linux
            goarch: amd64

          # Linux ARM64
          - name: linux-arm64
            goos: linux
            goarch: arm64

          # Linux MIPS (mipsel_24kc)
          - name: linux-mipsel
            goos: linux
            goarch: mipsle  # Little Endian (phù hợp cho mipsel_24kc)

    fail-fast: false
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      TAGS: with_clash_api,with_quic,with_grpc,with_wireguard,with_reality_server,with_v2ray_api,with_utls,with_ech,with_gvisor,with_dhcp

    steps:
      # Checkout source code
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Lấy phiên bản Go mới nhất
      - name: Get Latest Go Version
        id: version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

      # Thiết lập Go
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ steps.version.outputs.go_version }}

      # Build sing-box
      - name: Build sing-box
        id: build
        run: |
          echo "Building for GOARCH=${{ matrix.goarch }} GOOS=${{ matrix.goos }}"
          go build -tags "${{ env.TAGS }}" -o sing-box-${{ matrix.name }} ./cmd/sing-box

      # Đổi tên và nén file binary
      - name: Rename and Compress Artifacts
        run: |
          ls -R
          artifact_name=sing-box-${{ matrix.name }}.zip
          7z a $artifact_name sing-box-${{ matrix.name }}
          echo "artifact_name=$artifact_name" >> $GITHUB_ENV

      # Upload artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: ${{ env.artifact_name }}

  release:
    name: Create Release
    needs: cross
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Đặt biến môi trường cho tên và tag
      - name: Set Variables
        run: |
          TZ="Asia/Ho_Chi_Minh"
          RELEASE_NAME=$(TZ=$TZ date '+%d/%m/%Y %H:%M')
          TAG_NAME=$(TZ=$TZ date '+%Y%m%d%H%M')
          echo "RELEASE_NAME=${RELEASE_NAME}" >> $GITHUB_ENV
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        shell: bash

      # Tạo ghi chú phát hành
      - name: Create Release Notes
        run: |
          echo -e "👉 Github: thaomtam\n👉 Facebook: thời tiết\n👉 Telegram: t.me/ktandroidreview\n\n😍😍 Sing-Box core" > release-notes.txt

      # Kiểm tra nếu release đã tồn tại
      - name: Check If Release Exists
        id: check_release
        run: |
          if gh release view ${{ env.TAG_NAME }}; then
            echo "RELEASE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "RELEASE_EXISTS=false" >> $GITHUB_ENV
          fi

      # Download artifacts từ bước build
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts/

      # Tạo hoặc cập nhật Release
      - name: Create or Update Release
        run: |
          files=$(find ./artifacts -name "*.zip")
          if [ "${{ env.RELEASE_EXISTS }}" = "false" ]; then
            gh release create ${{ env.TAG_NAME }} \
              --generate-notes \
              --latest \
              --title "Build bởi Thời Tiết - ${{ env.RELEASE_NAME }}" \
              --notes-file release-notes.txt \
              $files
          else
            gh release upload ${{ env.TAG_NAME }} \
              $files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
